name: Pentaho npm registry authentication
description: Authenticate to the Pentaho npm registry.
inputs:
  pentaho_registry:
    description: URL to the Pentaho npm registry
    required: true
  username:
    description: Username for the Pentaho npm registry
    required: true
  password:
    description: Password for the Pentaho npm registry
    required: true
runs:
  using: "composite"
  steps:
    - name: NPM Artifactory authentication
      shell: bash
      run: |
        PASSWORD=$(echo -n "${{ inputs.password }}" | base64 | tr -d " \t\n\r")
        npm config set ${{ inputs.pentaho_registry }}:_password=$PASSWORD
        npm config set ${{ inputs.pentaho_registry }}:username=${{ inputs.username }}
