# ******************************************************************************
#
# Pentaho
#
# Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
#
# Use of this software is governed by the Business Source License included
# in the LICENSE.TXT file.
#
# Change Date: 2030-06-15
# ******************************************************************************
name: Configure Git
description: Configure global Git settings
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
