name: Detect npm usage
description: Detect whether npm is available and any package.json exists
outputs:
  has_npm:
    description: "true if npm present and at least one package.json found"
    value: ${{ steps.detect.outputs.has_npm }}
runs:
  using: composite
  steps:
    - id: detect
      shell: bash
      run: |
        set -euo pipefail
        if command -v npm >/dev/null 2>&1 && find . -type f -name package.json -print -quit | grep -q .; then
          echo "has_npm=true" >> "$GITHUB_OUTPUT"
        else
          echo "has_npm=false" >> "$GITHUB_OUTPUT"
        fi
