name: Check Commit Messages

on:
  workflow_call:

jobs:
  # Check commit messages against conventional commits specification
  check-commit-message:
    name: Check Commit Messages
    runs-on: [ k8s ]
    steps:
      - name: Check message against regex
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '(?:feat|fix|perf|revert|docs|style|chore|refactor|test|build|ci|improvement)(?:\([a-zA-Z_0-9-]+\))?:\s[a-z]{1,2}.+'
          error: "The commit message must follow the conventional commits specification"
          excludeDescription: "true" # optional: this excludes the description body of a pull request
          excludeTitle: "true" # optional: this excludes the title of a pull request
          checkAllCommitMessages: "true" # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # GitHub access token is only required if checkAllCommitMessages is true
